### PR TITLE
Update to v3.1.0 to use 2021 TIGER/Line Shapefiles

### PR DESCRIPTION
**Pull request by kprybol**
Rebuilt and rehosted geocoder.db using 2021 TIGER/Line Shapefiles. Will update readme on Degauss website with information on how to reproduce in the future. Updated references to v3.0.2 to 3.1.0. Successfully tested Docker build locally. Successfully tested geocoder on both address files.

### CODE REVIEW

**Comment by cole-brokamp** [comment]
:fire: :fire: :fire:  wow, amazing work!

is it okay if we copy the database file from your S3 location and host it ourselves? -- and then also reference that new location in the dockerfile?  If so, I'd like to make those changes in a new branch just so we can deploy the test release container and test it on some address data locally to compare what might be different when using the newer TIGER/Line files.

**Comment by cole-brokamp** [comment]
@erikarasnick, I'll also want your review and testing of the new release as well.

**Comment by cole-brokamp** [comment]
I've merged this into a new branch and we can continue to work it over there, thanks! #26

**Comment by kprybol** [comment]
@cole-brokamp - 100% would prefer to move the new db to your S3 bucket. I did some spot checking to make sure things were actually updated. Ex. `select * from range order by tlid asc limit 5;` in the 2021 db versus the same in the 2019 db. This will highlight a few changes to address ranges in the 36915 ZIP code. One thing to note, the `places` table doesn't get updated when rebuilding the database and appears to have been manually populated by `/build/sql/place.sql` rather than being tied to anything in the TIGER files. It didn't look like this table was being referenced at all when performing the geocoding, but I can look into how to update it should it actually needed.  Appreciate the work put in to release this as a Docker image! Has been a huge help, particularly when running this at scale (10's of millions of records).

**Comment by cole-brokamp** [comment]
great!  thank you again for this work.  agreed with you about the `place.sql`... probably not worth touching since it doesn't appear to be used.

unless, we see anything super crazy from @andrew-vancil or @erikarasnick , I expect to merge this later today.

**Pull request merged**
