### PR TITLE
2021 tiger line updates; mappp v1.0.0 on CRAN; closes #20

### LINKED ISSUE #20: implement {mappp}
implement [mappp](https://github.com/cole-brokamp/mappp) here and in other containers

### PR DESCRIPTION
**Pull request by cole-brokamp**
continued from #25

### CODE REVIEW

**Comment by cole-brokamp** [comment]
@erikarasnick and @andrew-vancil, could you both please try this out on a recent geocoding that you did?  you can use `ghcr.io/degauss-org/geocoder:2021-tiger-line` to test this update to the 2021 lines.  knowing its impossible to compare everything between the current version and this version, I still want to get a feel for how our results change.

**Comment by andrew-vancil** [comment]
I just ran this on the iron dataset and my geocode_result table is exactly the same as before. I compared the lat/lon columns from each version and it looks like there are no discrepancies. Looking good to me!

**Comment by cole-brokamp** [comment]
I also just ran on something on about 400 real addresses and got the exact same results too.

**Comment by erikarasnick** [comment]
Also for reference, that was only 1 of almost 900 addresses

**Comment by cole-brokamp** [comment]
sounds good.  will you approve through the code review request and then we can merge in and release?

**Review by erikarasnick — APPROVED** [review]

**Pull request merged**
